name: molnextr
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio
  - pip:
      - molscribe==1.1.1
      - rdkit==2023.9.1
      - jupyter
      - pandas
      - numpy
      - matplotlib
      - pillow
      - opencv-python
      - easyocr
      - layoutparser
      - transformers
      - pytorch-lightning==1.9.0
      - torchmetrics==0.11.4